const DEFAULT_CONSENT = '본인은 본 교육자료 및 교육내용을 확인하였으며, 본 전자서명이 교육 이수 확인을 위한 본인의 서명으로 사용되는 것에 동의합니다.';
const LEGAL_EDU_TYPES = ['산업안전보건교육','직장 내 괴롭힘 예방교육','성희롱 예방교육','개인정보보호교육','장애인 인식개선교육','퇴직연금교육','소방안전교육','응급처치교육','기타/수시교육 직접입력'];
let CONFIG = null;
let currentAdminSession = null;
let state = { employees: [], educations: [], sessions: [], targets: [], signatures: [] };
let currentEmployee = null;
let selectedSignEducationId = null;
let signaturePad = null;
let targetDraftKey = null;
let targetDraftSelection = new Set();
let editingEducationId = null;
let editingSessionId = null;

const $ = id => document.getElementById(id);
function normalizeText(v){ return String(v ?? '').trim(); }
function normalizePhone(v){ return String(v ?? '').replace(/[^0-9]/g,''); }
function normalizeWorkType(v){ const raw = normalizeText(v); if(raw==='주간') return '1반'; if(raw==='야간') return '2반'; if(raw==='상시'||raw==='기타') return '주간 정취'; return ['1반','2반','주간 정취'].includes(raw) ? raw : (raw || '주간 정취'); }
function escapeHtml(s){ return String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function alertMsg(msg){ alert(msg); }
function todayDate(){ const d=new Date(); const p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`; }
function formatDateTime(iso){ if(!iso) return ''; const d=new Date(iso); if(Number.isNaN(d.getTime())) return iso; const p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`; }
function maskPhone(v){ const p=normalizePhone(v); return p.length<8 ? p : `${p.slice(0,3)}-****-${p.slice(-4)}`; }
function getEdu(id){ return state.educations.find(x=>x.id===id); }
function getEmp(id){ return state.employees.find(x=>x.id===id); }
function getSession(id){ return state.sessions.find(x=>x.id===id); }
function sessionsByEdu(educationId){ return state.sessions.filter(s=>s.education_id===educationId); }
function targetsBySession(sessionId){ return state.targets.filter(t=>t.session_id===sessionId); }
function targetEmployeeIdsForEdu(educationId){ return new Set(state.targets.filter(t=>t.education_id===educationId).map(t=>t.employee_id)); }
function targetsByEdu(educationId){ return [...targetEmployeeIdsForEdu(educationId)].map(employee_id=>({ education_id:educationId, employee_id, target_status:'대상' })); }
function signaturesByEdu(educationId){ return state.signatures.filter(s=>s.education_id===educationId); }
function signatureFor(educationId, employeeId){ return state.signatures.find(s=>s.education_id===educationId && s.employee_id===employeeId); }
function signatureForSession(sessionId, employeeId){ return state.signatures.find(s=>s.session_id===sessionId && s.employee_id===employeeId); }
function sessionLabel(session){ if(!session) return ''; const no=normalizeText(session.session_no||''); const name=normalizeText(session.session_name||''); return (!name || name===no) ? no : `${no} ${name}`.trim(); }
function sessionFullTitle(edu, session){ if(!edu) return ''; const no=normalizeText(session?.session_no||''); if(!no) return edu.title; return String(edu.title||'').includes(`(${no})`) ? edu.title : `${edu.title} (${no})`; }
function safeFileName(name){ return name.replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_'); }
function thinBorder(){ return { top:{style:'thin'}, left:{style:'thin'}, bottom:{style:'thin'}, right:{style:'thin'} }; }

async function initConfig(){
  const res = await fetch('/api/config');
  if(!res.ok) throw new Error('Vercel 환경변수 설정을 확인해 주세요.');
  CONFIG = await res.json();
  if(!CONFIG.supabaseUrl || !CONFIG.supabaseKey) throw new Error('Supabase 환경변수가 없습니다.');
}
function activeBearer(){ return currentAdminSession?.access_token || CONFIG.supabaseKey; }
function restHeaders(extra={}){ return { apikey: CONFIG.supabaseKey, Authorization: `Bearer ${activeBearer()}`, 'Content-Type':'application/json', ...extra }; }
async function authSignIn(email, password){
  const res = await fetch(`${CONFIG.supabaseUrl}/auth/v1/token?grant_type=password`, {
    method:'POST',
    headers:{ apikey: CONFIG.supabaseKey, 'Content-Type':'application/json' },
    body: JSON.stringify({ email, password })
  });
  if(!res.ok){ throw new Error('관리자 이메일 또는 비밀번호가 맞지 않습니다.'); }
  return await res.json();
}
async function authLogout(){
  if(currentAdminSession?.access_token){
    try{ await fetch(`${CONFIG.supabaseUrl}/auth/v1/logout`, { method:'POST', headers:{ apikey: CONFIG.supabaseKey, Authorization:`Bearer ${currentAdminSession.access_token}` } }); }catch(e){}
  }
  currentAdminSession = null;
  sessionStorage.removeItem('sewon_admin_session');
}
async function ensureAdminUser(session){
  const user = session?.user;
  if(!user?.id) throw new Error('관리자 사용자 정보를 확인할 수 없습니다.');
  const rows = await db('admin_users', { query:`?select=*&auth_user_id=eq.${encodeURIComponent(user.id)}&is_active=eq.true` });
  if(!rows?.length) throw new Error('관리자 권한이 등록되지 않은 계정입니다. Supabase admin_users 테이블을 확인해 주세요.');
  return rows[0];
}
async function db(table, { method='GET', query='', body=null, prefer='' }={}){
  const url = `${CONFIG.supabaseUrl}/rest/v1/${table}${query}`;
  const headers = restHeaders(prefer ? { Prefer: prefer } : {});
  const res = await fetch(url, { method, headers, body: body ? JSON.stringify(body) : undefined });
  if(!res.ok){ const txt = await res.text(); throw new Error(`${table} ${method} 실패: ${txt}`); }
  if(res.status===204) return null;
  const text = await res.text();
  return text ? JSON.parse(text) : null;
}
async function loadAllData(){
  const [employees, educations, sessions, targets, signatures] = await Promise.all([
    db('employees',{query:'?select=*'}), db('educations',{query:'?select=*'}), db('education_sessions',{query:'?select=*'}), db('education_targets',{query:'?select=*'}), db('education_signatures',{query:'?select=*'})
  ]);
  state = { employees: employees||[], educations: educations||[], sessions: sessions||[], targets: targets||[], signatures: signatures||[] };
}
async function refreshAndRender(){ await loadAllData(); renderAllAdmin(); if(currentEmployee) renderMyEducations(); }

function currentEduType(){ return $('eduTypeSelect')?.value === '기타/수시교육 직접입력' ? normalizeText($('eduTypeCustom')?.value || '') : ($('eduTypeSelect')?.value || ''); }
function periodDetailOptions(period){ if(period==='월간') return Array.from({length:12},(_,i)=>`${i+1}월`); if(period==='분기') return ['1분기','2분기','3분기','4분기']; if(period==='반기') return ['상반기','하반기']; if(period==='연간') return ['연간']; if(period==='수시') return ['수시']; return ['']; }
function updatePeriodDetailOptions(){ const periodEl=$('eduPeriod'), detailEl=$('eduPeriodDetail'); if(!periodEl || !detailEl) return; const prev=detailEl.value; const opts=periodDetailOptions(periodEl.value); detailEl.innerHTML=opts.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join(''); if(opts.includes(prev)) detailEl.value=prev; }
function buildEducationTitle(){ const year=normalizeText($('eduYear')?.value || new Date().getFullYear()); const type=currentEduType(); const detail=normalizeText($('eduPeriodDetail')?.value || ''); const parts=[`${year}년`]; if(detail && detail!=='연간') parts.push(detail); if(detail==='연간') parts.push('연간'); if(type) parts.push(type); return parts.join(' ').trim(); }
function getSessionNoValue(){ const sel=$('sessionNo'), custom=$('sessionNoCustom'); if(!sel) return ''; return sel.value==='직접입력' ? normalizeText(custom?.value || '') : sel.value; }
function updateEducationTitlePreview(){ const customWrap=$('eduTypeCustomWrap'), typeSel=$('eduTypeSelect'); if(customWrap && typeSel) customWrap.classList.toggle('hidden', typeSel.value!=='기타/수시교육 직접입력'); updatePeriodDetailOptions(); if($('eduTitle')) $('eduTitle').value = buildEducationTitle(); updateSessionTitlePreview(); }
function updateSessionTitlePreview(){ const preview=$('sessionTitlePreview'); if(!preview) return; preview.value = sessionFullTitle({title:buildEducationTitle()}, {session_no:getSessionNoValue() || '1차'}); const customWrap=$('sessionNoCustomWrap'), noSel=$('sessionNo'); if(customWrap && noSel) customWrap.classList.toggle('hidden', noSel.value!=='직접입력'); }
function initEduTypeOptions(){ const sel=$('eduTypeSelect'); if(!sel) return; sel.innerHTML = LEGAL_EDU_TYPES.map((v,i)=>`<option value="${escapeHtml(v)}" ${i===0?'selected':''}>${escapeHtml(v)}</option>`).join(''); }
function setSessionNoControl(value){ const sel=$('sessionNo'), custom=$('sessionNoCustom'); if(!sel) return; const opts=Array.from(sel.options).map(o=>o.value); if(opts.includes(value)){ sel.value=value; if(custom) custom.value=''; } else { sel.value='직접입력'; if(custom) custom.value=value||''; } updateSessionTitlePreview(); }
function clearSessionFields(){ ['sessionDate','sessionLocation','sessionStart','sessionEnd','sessionNoCustom'].forEach(id=>{ if($(id)) $(id).value=''; }); if($('sessionNo')) $('sessionNo').value='1차'; if($('sessionStatus')) $('sessionStatus').value='서명가능'; updateSessionTitlePreview(); }
function currentFormEducation(){ if(editingEducationId) return getEdu(editingEducationId); const title=buildEducationTitle(); return state.educations.find(e=>e.title===title); }
function currentFormSession(){ if(editingSessionId) return getSession(editingSessionId); const edu=currentFormEducation(); const no=getSessionNoValue(); return edu && no ? state.sessions.find(s=>s.education_id===edu.id && s.session_no===no) : null; }
function formTargetKey(){ const ses=currentFormSession(); if(ses) return `session:${ses.id}`; return `newsession:${buildEducationTitle()}:${getSessionNoValue()||'1차'}`; }
function setEducationEditMode(educationId=null, sessionId=null){ editingEducationId=educationId; editingSessionId=sessionId; updateEducationEditBanner(); }
function updateEducationEditBanner(){ const banner=$('educationEditBanner'), saveBtn=$('saveIntegratedEducationBtn'); if(!banner||!saveBtn) return; if(editingEducationId){ const edu=getEdu(editingEducationId); const ses=editingSessionId?getSession(editingSessionId):null; banner.classList.remove('hidden'); banner.innerHTML = `<b>수정 모드</b> · ${escapeHtml(edu?.title||'')}${ses?` · ${escapeHtml(ses.session_no||'')} 회차 수정 중`:' · 교육 기본정보 수정 중'}<br><span>신규 등록은 ‘입력 초기화’를 누른 뒤 저장해 주세요.</span>`; saveBtn.textContent = editingSessionId ? '교육/회차/대상자 수정 저장' : '교육 기본정보 수정 저장'; } else { banner.classList.add('hidden'); banner.textContent=''; saveBtn.textContent='교육/회차/대상자 저장'; } }

function showLogin(){ $('loginScreen').classList.remove('hidden'); $('adminDashboard').classList.add('hidden'); $('employeeDashboard').classList.add('hidden'); }
async function showAdmin(){ $('loginScreen').classList.add('hidden'); $('adminDashboard').classList.remove('hidden'); $('employeeDashboard').classList.add('hidden'); const adminLabel = $('adminUserLabel'); if(adminLabel) adminLabel.textContent = currentAdminSession?.user?.email || '관리자'; await refreshAndRender(); }
async function showEmployee(emp){ currentEmployee=emp; $('loginScreen').classList.add('hidden'); $('adminDashboard').classList.add('hidden'); $('employeeDashboard').classList.remove('hidden'); $('loggedEmployeeName').textContent=`${emp.name} 님`; $('loggedEmployeeMeta').textContent=`${emp.department||'-'} · ${emp.employee_no}`; await loadAllData(); renderMyEducations(); }
function initTabs(){ document.querySelectorAll('[data-login-tab]').forEach(btn=>btn.addEventListener('click',()=>{ document.querySelectorAll('[data-login-tab]').forEach(b=>b.classList.remove('active')); document.querySelectorAll('.login-panel').forEach(p=>p.classList.remove('active')); btn.classList.add('active'); $(btn.dataset.loginTab).classList.add('active'); })); }
function initNav(){ document.querySelectorAll('.nav[data-view]').forEach(btn=>btn.addEventListener('click',async()=>{ document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.remove('active')); document.querySelectorAll('#adminDashboard .view').forEach(v=>v.classList.remove('active')); btn.classList.add('active'); $(btn.dataset.view).classList.add('active'); await refreshAndRender(); })); }
function renderAllAdmin(){ fillEducationSelects(); renderEmployees(); renderEducations(); renderSessions(); renderTargetDeptOptions(); renderTargets(); renderStatus(); }

function initLogins(){
  const saved = sessionStorage.getItem('sewon_admin_session');
  if(saved){
    try{ currentAdminSession = JSON.parse(saved); }catch(e){ currentAdminSession = null; }
  }
  $('adminLoginBtn').addEventListener('click', async()=>{
    try{
      const email = normalizeText($('adminId').value);
      const password = $('adminPassword').value;
      if(!email || !password) return alertMsg('관리자 이메일과 비밀번호를 입력해 주세요.');
      const session = await authSignIn(email, password);
      currentAdminSession = session;
      await ensureAdminUser(session);
      sessionStorage.setItem('sewon_admin_session', JSON.stringify(session));
      $('adminPassword').value = '';
      await showAdmin();
    }catch(e){
      currentAdminSession = null;
      sessionStorage.removeItem('sewon_admin_session');
      alertMsg(e.message);
    }
  });
  $('employeeLoginBtn').addEventListener('click', async()=>{ try{ const name=normalizeText($('empLoginName').value); const no=normalizeText($('empLoginNo').value); const phone=normalizePhone($('empLoginPhone').value); const q=`?select=*&name=eq.${encodeURIComponent(name)}&employee_no=eq.${encodeURIComponent(no)}&phone_number=eq.${encodeURIComponent(phone)}&employment_status=neq.${encodeURIComponent('퇴사')}`; const rows=await db('employees',{query:q}); const emp=rows?.[0]; if(!emp) return alertMsg('직원 정보가 일치하지 않거나 퇴사 상태입니다. 관리자에게 문의해 주세요.'); await showEmployee(emp); }catch(e){ alertMsg(e.message); } });
  $('adminLogoutBtn').addEventListener('click', async()=>{ await authLogout(); showLogin(); });
  $('employeeLogoutBtn').addEventListener('click',()=>{ currentEmployee=null; showLogin(); });
}

function employeeRowFromObject(row){ return { employee_no:normalizeText(row['사번']??row.employee_no??row['Employee No']??row.NO??row.No), name:normalizeText(row['이름']??row['성명']??row.name??row.Name), department:normalizeText(row['부서']??row.department??row.Department), phone_number:normalizePhone(row['휴대폰번호']??row['휴대폰 번호']??row['전화번호']??row.phone_number??row.Phone), shift_type:normalizeWorkType(row['근무형태']??row['근무조']??row.shift_type??row.Shift??'주간 정취'), employment_status:normalizeText(row['재직상태']??row.employment_status??row.Status??'재직')||'재직', hire_date:normalizeText(row['입사일']??row.hire_date??'')||null, resign_date:normalizeText(row['퇴사일']??row.resign_date??'')||null }; }
async function importEmployeesFromRows(rows){ let skipped=0; const payload=[]; rows.forEach(raw=>{ const r=employeeRowFromObject(raw); if(!r.employee_no||!r.name||!r.department||!r.phone_number){ skipped++; return; } payload.push(r); }); if(payload.length) await db('employees',{method:'POST',query:'?on_conflict=employee_no',body:payload,prefer:'resolution=merge-duplicates,return=representation'}); await refreshAndRender(); alertMsg(`직원 업로드 완료\n처리: ${payload.length}명\n건너뜀: ${skipped}건`); }
function initEmployeeActions(){
  $('importEmployeesBtn').addEventListener('click',()=>{ const file=$('employeeExcel').files[0]; if(!file) return alertMsg('업로드할 엑셀 파일을 선택해 주세요.'); const reader=new FileReader(); reader.onload=e=>{ const data=new Uint8Array(e.target.result); const wb=XLSX.read(data,{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; importEmployeesFromRows(XLSX.utils.sheet_to_json(ws,{defval:''})).catch(err=>alertMsg(err.message)); }; reader.readAsArrayBuffer(file); });
  $('downloadEmployeeTemplateBtn').addEventListener('click',()=>{ const ws=XLSX.utils.aoa_to_sheet([['사번','이름','부서','휴대폰번호','근무형태','재직상태','입사일','퇴사일']]); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Employees'); XLSX.writeFile(wb,'employee_upload_template.xlsx'); });
  $('addEmployeeBtn').addEventListener('click',async()=>{ try{ const payload={ employee_no:normalizeText($('newEmpNo').value), name:normalizeText($('newEmpName').value), department:normalizeText($('newEmpDept').value), phone_number:normalizePhone($('newEmpPhone').value), shift_type:normalizeWorkType($('newEmpShift').value), employment_status:'재직' }; if(!payload.employee_no||!payload.name||!payload.department||!payload.phone_number) return alertMsg('사번, 이름, 부서, 휴대폰번호를 모두 입력해 주세요.'); await db('employees',{method:'POST',body:payload,prefer:'return=representation'}); ['newEmpNo','newEmpName','newEmpDept','newEmpPhone'].forEach(id=>$(id).value=''); await refreshAndRender(); }catch(e){ alertMsg(e.message); } });
  ['employeeSearch','employeeStatusFilter','employeeShiftFilter'].forEach(id=>$(id).addEventListener('input',renderEmployees));
}
function filteredEmployees(prefix='employee'){ const search=normalizeText($(`${prefix}Search`)?.value||'').toLowerCase(); const status=$(`${prefix}StatusFilter`)?.value ?? ($(`${prefix}OnlyActive`)?.value ?? ''); const shift=$(`${prefix}ShiftFilter`)?.value ?? ''; const dept=$(`${prefix}DeptFilter`)?.value ?? ''; return state.employees.filter(e=>{ const hay=`${e.employee_no} ${e.name} ${e.department}`.toLowerCase(); if(search&&!hay.includes(search)) return false; if(status&&e.employment_status!==status) return false; if(shift&&e.shift_type!==shift) return false; if(dept&&e.department!==dept) return false; return true; }); }
function renderEmployees(){ const rows=filteredEmployees('employee'); const table=$('employeeTable'); table.innerHTML=`<thead><tr><th>사번</th><th>이름</th><th>부서</th><th>휴대폰</th><th>근무형태</th><th>상태</th><th>관리</th></tr></thead><tbody></tbody>`; const tb=table.querySelector('tbody'); rows.forEach(e=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${escapeHtml(e.employee_no)}</td><td>${escapeHtml(e.name)}</td><td>${escapeHtml(e.department)}</td><td class="phone-mask">${escapeHtml(maskPhone(e.phone_number))}</td><td>${escapeHtml(e.shift_type||'')}</td><td><span class="pill ${e.employment_status==='재직'?'ok':'no'}">${escapeHtml(e.employment_status||'')}</span></td><td></td>`; const td=tr.lastElementChild; const toggle=document.createElement('button'); toggle.className='action-btn'; toggle.textContent=e.employment_status==='퇴사'?'재직처리':'퇴사처리'; toggle.onclick=async()=>{ await db('employees',{method:'PATCH',query:`?id=eq.${e.id}`,body:{employment_status:e.employment_status==='퇴사'?'재직':'퇴사',resign_date:e.employment_status==='퇴사'?null:todayDate()},prefer:'return=representation'}); await refreshAndRender(); }; const del=document.createElement('button'); del.className='action-btn'; del.textContent='완전삭제'; del.onclick=async()=>{ const hasHistory=state.signatures.some(s=>s.employee_id===e.id)||state.targets.some(t=>t.employee_id===e.id); if(hasHistory) return alertMsg('교육 대상/서명 이력이 있어 완전삭제할 수 없습니다. 퇴사처리를 사용해 주세요.'); if(confirm('정말 삭제하시겠습니까?')){ await db('employees',{method:'DELETE',query:`?id=eq.${e.id}`}); await refreshAndRender(); } }; td.append(toggle,del); tb.appendChild(tr); }); }

function initEducationActions(){ initEduTypeOptions(); if($('eduConsent')) $('eduConsent').value=DEFAULT_CONSENT; updateEducationTitlePreview(); ['eduTypeSelect','eduTypeCustom','eduYear','eduPeriod','eduPeriodDetail'].forEach(id=>{ const el=$(id); if(el){ el.addEventListener('input',()=>{ syncTargetDraftFromDom(); if(!editingEducationId) targetDraftKey=null; updateEducationTitlePreview(); renderTargets(); }); el.addEventListener('change',()=>{ syncTargetDraftFromDom(); if(!editingEducationId) targetDraftKey=null; updateEducationTitlePreview(); renderTargets(); }); } }); $('saveIntegratedEducationBtn')?.addEventListener('click',()=>saveIntegratedEducation().catch(e=>alertMsg(e.message))); $('clearEducationFormBtn')?.addEventListener('click',()=>clearEducationForm(true)); const newBtn=$('newEducationBtn'); if(newBtn) newBtn.addEventListener('click',()=>clearEducationForm(true)); }
function ensureTargetDraftForCurrentEducation(){ const key=formTargetKey(); if(targetDraftKey===key) return; syncTargetDraftFromDom(); const existingSession=currentFormSession(); targetDraftSelection=new Set(existingSession ? targetsBySession(existingSession.id).map(t=>t.employee_id) : []); targetDraftKey=key; }
function syncTargetDraftFromDom(){ const table=$('targetTable'); if(!table||!targetDraftKey) return; table.querySelectorAll('tbody input[type=checkbox]').forEach(ch=>{ if(ch.checked) targetDraftSelection.add(ch.value); else targetDraftSelection.delete(ch.value); }); }
async function getOrCreateEducationFromForm(){ updateEducationTitlePreview(); const title=normalizeText($('eduTitle')?.value||''); const education_type=currentEduType(); if(!education_type) throw new Error('법정교육 구분 또는 수시/기타 교육명을 입력해 주세요.'); if(!title) throw new Error('교육명이 자동 생성되지 않았습니다.'); let edu=editingEducationId ? getEdu(editingEducationId) : state.educations.find(e=>e.title===title); const payload={ title, education_type, year:normalizeText($('eduYear').value), period:$('eduPeriod').value, period_detail:$('eduPeriodDetail').value, summary:$('eduSummary').value.trim(), consent_text:$('eduConsent').value.trim()||DEFAULT_CONSENT, status: edu?.status || '진행' }; if(edu){ const rows=await db('educations',{method:'PATCH',query:`?id=eq.${edu.id}`,body:payload,prefer:'return=representation'}); Object.assign(edu, rows?.[0]||payload); return edu; } const rows=await db('educations',{method:'POST',body:payload,prefer:'return=representation'}); edu=rows[0]; state.educations.push(edu); return edu; }
async function saveIntegratedEducation(){ syncTargetDraftFromDom(); const edu=await getOrCreateEducationFromForm(); const session_no=getSessionNoValue()||`${sessionsByEdu(edu.id).length+1}차`; const education_date=$('sessionDate').value; const start_time=$('sessionStart').value || null; const end_time=$('sessionEnd').value || null; const location=normalizeText($('sessionLocation').value); const status=$('sessionStatus').value; const hasInput=!!(education_date||start_time||end_time||location); if(editingEducationId && !editingSessionId && !hasInput){ clearEducationForm(true); await refreshAndRender(); return alertMsg(`교육 기본정보가 수정되었습니다.\n${edu.title}`); } if(!education_date) return alertMsg('교육일자를 입력해 주세요.'); let savedSession = editingSessionId ? getSession(editingSessionId) : state.sessions.find(s=>s.education_id===edu.id && s.session_no===session_no); const sessionPayload={ education_id:edu.id, session_no, session_name:session_no, education_date, start_time, end_time, location, target_shift:'선택대상', status }; if(savedSession){ const rows=await db('education_sessions',{method:'PATCH',query:`?id=eq.${savedSession.id}`,body:sessionPayload,prefer:'return=representation'}); savedSession=rows?.[0] || {...savedSession,...sessionPayload}; } else { const rows=await db('education_sessions',{method:'POST',body:sessionPayload,prefer:'return=representation'}); savedSession=rows[0]; }
  const signedIds=new Set(state.signatures.filter(s=>s.session_id===savedSession.id).map(s=>s.employee_id)); let kept=0; signedIds.forEach(id=>{ if(!targetDraftSelection.has(id)){ targetDraftSelection.add(id); kept++; } }); await db('education_targets',{method:'DELETE',query:`?session_id=eq.${savedSession.id}`}); const targets=[...targetDraftSelection].map(employee_id=>({education_id:edu.id,session_id:savedSession.id,employee_id,target_status:'대상'})); if(targets.length) await db('education_targets',{method:'POST',body:targets,prefer:'return=representation'}); const msg=`저장되었습니다.\n${sessionFullTitle(edu,savedSession)}\n회차별 대상자: ${targets.length}명${kept?`\n\n서명 이력이 있는 ${kept}명은 증빙 보존을 위해 유지했습니다.`:''}`; clearEducationForm(true); await refreshAndRender(); if($('statusEducationSelect')) $('statusEducationSelect').value=edu.id; fillStatusSessionSelect(); if($('statusSessionSelect')) $('statusSessionSelect').value=savedSession.id; renderStatus(); alertMsg(msg); }
function clearEducationForm(resetEdit=true){ $('eduTypeSelect').value=LEGAL_EDU_TYPES[0]; $('eduTypeCustom').value=''; $('eduYear').value=new Date().getFullYear(); $('eduPeriod').value='연간'; updatePeriodDetailOptions(); $('eduPeriodDetail').value='연간'; $('eduSummary').value=''; $('eduConsent').value=DEFAULT_CONSENT; clearSessionFields(); targetDraftKey=null; targetDraftSelection=new Set(); if(resetEdit) setEducationEditMode(null,null); updateEducationTitlePreview(); renderTargets(); }
function renderEducations(){ const table=$('educationTable'); table.innerHTML=`<thead><tr><th>교육명</th><th>구분</th><th>연도</th><th>주기</th><th>세부</th><th>회차</th><th>대상</th><th>상태</th><th>관리</th></tr></thead><tbody></tbody>`; const tb=table.querySelector('tbody'); state.educations.forEach(e=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${escapeHtml(e.title)}</td><td>${escapeHtml(e.education_type||'')}</td><td>${escapeHtml(e.year||'')}</td><td>${escapeHtml(e.period||'')}</td><td>${escapeHtml(e.period_detail||'')}</td><td>${sessionsByEdu(e.id).length}</td><td>${targetEmployeeIdsForEdu(e.id).size}</td><td><span class="pill">${escapeHtml(e.status||'')}</span></td><td></td>`; const td=tr.lastElementChild; const load=document.createElement('button'); load.className='action-btn'; load.textContent='수정'; load.onclick=()=>loadEducationToForm(e.id); const close=document.createElement('button'); close.className='action-btn'; close.textContent=e.status==='마감'?'진행처리':'마감'; close.onclick=async()=>{ await db('educations',{method:'PATCH',query:`?id=eq.${e.id}`,body:{status:e.status==='마감'?'진행':'마감'},prefer:'return=representation'}); await refreshAndRender(); }; const del=document.createElement('button'); del.className='action-btn'; del.textContent='삭제'; del.onclick=async()=>{ if(state.signatures.some(s=>s.education_id===e.id)) return alertMsg('서명 이력이 있어 삭제할 수 없습니다. 마감 처리해 주세요.'); if(confirm('교육과 연결된 회차/대상자 정보를 삭제하시겠습니까?')){ await db('educations',{method:'DELETE',query:`?id=eq.${e.id}`}); await refreshAndRender(); } }; td.append(load,close,del); tb.appendChild(tr); }); }
function loadEducationToForm(educationId){ const e=getEdu(educationId); if(!e) return; setEducationEditMode(e.id,null); if(LEGAL_EDU_TYPES.includes(e.education_type)){ $('eduTypeSelect').value=e.education_type; $('eduTypeCustom').value=''; } else { $('eduTypeSelect').value='기타/수시교육 직접입력'; $('eduTypeCustom').value=e.education_type||''; } $('eduYear').value=e.year||new Date().getFullYear(); $('eduPeriod').value=e.period||'연간'; updatePeriodDetailOptions(); $('eduPeriodDetail').value=e.period_detail||'연간'; $('eduSummary').value=e.summary||''; $('eduConsent').value=e.consent_text||DEFAULT_CONSENT; clearSessionFields(); targetDraftKey=null; updateEducationTitlePreview(); renderTargets(); if($('sessionEducationSelect')) $('sessionEducationSelect').value=e.id; renderSessions(); document.querySelector('[data-view="educationManageView"]')?.click(); }
function loadSessionToForm(sessionId){ const s=getSession(sessionId); if(!s) return; loadEducationToForm(s.education_id); setEducationEditMode(s.education_id,s.id); setSessionNoControl(s.session_no||'1차'); $('sessionDate').value=s.education_date||''; $('sessionLocation').value=s.location||''; $('sessionStart').value=s.start_time||''; $('sessionEnd').value=s.end_time||''; $('sessionStatus').value=s.status||'서명가능'; targetDraftKey=null; ensureTargetDraftForCurrentEducation(); updateSessionTitlePreview(); renderTargets(); }
function fillEducationSelects(){ ['sessionEducationSelect','statusEducationSelect'].forEach(id=>{ const sel=$(id); if(!sel) return; const prev=sel.value; sel.innerHTML=''; state.educations.forEach(e=>{ const opt=document.createElement('option'); opt.value=e.id; opt.textContent=e.title; sel.appendChild(opt); }); if(prev && state.educations.some(e=>e.id===prev)) sel.value=prev; }); fillStatusSessionSelect(); }
function initSessionActions(){ ['sessionNo','sessionNoCustom','sessionDate','sessionLocation','sessionStart','sessionEnd','sessionStatus'].forEach(id=>{ const el=$(id); if(el){ el.addEventListener('input',()=>{ syncTargetDraftFromDom(); targetDraftKey=null; updateSessionTitlePreview(); renderTargets(); }); el.addEventListener('change',()=>{ syncTargetDraftFromDom(); targetDraftKey=null; updateSessionTitlePreview(); renderTargets(); }); } }); $('sessionEducationSelect')?.addEventListener('change',renderSessions); }
function renderSessions(){ const eduId=$('sessionEducationSelect')?.value; const table=$('sessionTable'); if(!table) return; table.innerHTML=`<thead><tr><th>회차별 교육명</th><th>교육일자</th><th>시간</th><th>장소</th><th>대상</th><th>서명</th><th>상태</th><th>관리</th></tr></thead><tbody></tbody>`; const tb=table.querySelector('tbody'); state.sessions.filter(s=>!eduId||s.education_id===eduId).sort((a,b)=>(a.education_date||'').localeCompare(b.education_date||'')).forEach(s=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${escapeHtml(sessionFullTitle(getEdu(s.education_id),s))}</td><td>${escapeHtml(s.education_date||'')}</td><td>${escapeHtml((s.start_time||'')+(s.end_time?`~${s.end_time}`:''))}</td><td>${escapeHtml(s.location||'')}</td><td>${targetsBySession(s.id).length}</td><td>${state.signatures.filter(x=>x.session_id===s.id).length}</td><td><span class="pill ${s.status==='서명가능'?'ok':(s.status==='마감'?'no':'warn')}">${escapeHtml(s.status||'')}</span></td><td></td>`; const td=tr.lastElementChild; const edit=document.createElement('button'); edit.className='action-btn'; edit.textContent='수정/대상자'; edit.onclick=()=>loadSessionToForm(s.id); td.appendChild(edit); ['예정','서명가능','마감'].forEach(st=>{ const btn=document.createElement('button'); btn.className='action-btn'; btn.textContent=st; btn.onclick=async()=>{ await db('education_sessions',{method:'PATCH',query:`?id=eq.${s.id}`,body:{status:st},prefer:'return=representation'}); await refreshAndRender(); }; td.appendChild(btn); }); const del=document.createElement('button'); del.className='action-btn'; del.textContent='삭제'; del.onclick=async()=>{ if(state.signatures.some(x=>x.session_id===s.id)) return alertMsg('해당 회차에 서명 이력이 있어 삭제할 수 없습니다.'); if(confirm('회차와 해당 회차의 대상자 정보를 삭제하시겠습니까?')){ await db('education_sessions',{method:'DELETE',query:`?id=eq.${s.id}`}); await refreshAndRender(); } }; td.appendChild(del); tb.appendChild(tr); }); }

function renderTargetDeptOptions(){ const sel=$('targetDeptFilter'); if(!sel) return; const prev=sel.value; const depts=[...new Set(state.employees.map(e=>e.department).filter(Boolean))].sort(); sel.innerHTML='<option value="">전체부서</option>'+depts.map(d=>`<option value="${escapeHtml(d)}">${escapeHtml(d)}</option>`).join(''); if(depts.includes(prev)) sel.value=prev; }
function targetFilteredEmployees(){ const search=normalizeText($('targetSearch')?.value||'').toLowerCase(); const dept=$('targetDeptFilter')?.value||''; const shift=$('targetShiftFilter')?.value||''; const status=$('targetOnlyActive')?.value||''; return state.employees.filter(e=>{ const hay=`${e.employee_no} ${e.name} ${e.department}`.toLowerCase(); if(search&&!hay.includes(search)) return false; if(dept&&e.department!==dept) return false; if(shift&&e.shift_type!==shift) return false; if(status&&e.employment_status!==status) return false; return true; }); }
function initTargetActions(){ ['targetSearch','targetDeptFilter','targetShiftFilter','targetOnlyActive'].forEach(id=>$(id)?.addEventListener('input',()=>{ syncTargetDraftFromDom(); renderTargets(); })); const bind=(id,fn)=>$(id)?.addEventListener('click',fn); bind('selectAllFilteredBtn',()=>{ ensureTargetDraftForCurrentEducation(); targetFilteredEmployees().forEach(e=>targetDraftSelection.add(e.id)); renderTargets(); }); bind('deselectAllFilteredBtn',()=>{ ensureTargetDraftForCurrentEducation(); targetFilteredEmployees().forEach(e=>targetDraftSelection.delete(e.id)); renderTargets(); }); bind('selectShift1Btn',()=>selectWorkTypeTargets('1반')); bind('selectShift2Btn',()=>selectWorkTypeTargets('2반')); bind('selectDayFixedBtn',()=>selectWorkTypeTargets('주간 정취')); bind('clearAllTargetsBtn',()=>{ ensureTargetDraftForCurrentEducation(); if(confirm('현재 회차의 선택 대상자를 모두 해제하시겠습니까?')){ targetDraftSelection.clear(); renderTargets(); } }); }
function selectWorkTypeTargets(workType){ ensureTargetDraftForCurrentEducation(); state.employees.filter(e=>e.shift_type===workType && e.employment_status==='재직').forEach(e=>targetDraftSelection.add(e.id)); renderTargets(); }
function renderTargets(){ ensureTargetDraftForCurrentEducation(); const rows=targetFilteredEmployees(); const table=$('targetTable'); if(!table) return; const existingEdu=currentFormEducation(); const existingSession=currentFormSession(); table.innerHTML=`<thead><tr><th>선택</th><th>사번</th><th>이름</th><th>부서</th><th>근무형태</th><th>상태</th><th>해당 회차 서명상태</th></tr></thead><tbody></tbody>`; const tb=table.querySelector('tbody'); rows.forEach(e=>{ const sig=existingSession ? signatureForSession(existingSession.id,e.id) : (existingEdu ? signatureFor(existingEdu.id,e.id) : null); const tr=document.createElement('tr'); tr.innerHTML=`<td><input type="checkbox" value="${e.id}" ${targetDraftSelection.has(e.id)?'checked':''}></td><td>${escapeHtml(e.employee_no)}</td><td>${escapeHtml(e.name)}</td><td>${escapeHtml(e.department)}</td><td>${escapeHtml(e.shift_type||'')}</td><td>${escapeHtml(e.employment_status||'')}</td><td>${sig?'<span class="pill ok">완료</span>':'<span class="pill no">미완료</span>'}</td>`; tr.querySelector('input').addEventListener('change',ev=>{ if(ev.target.checked) targetDraftSelection.add(e.id); else targetDraftSelection.delete(e.id); }); tb.appendChild(tr); }); }

function initStatusActions(){ ['statusEducationSelect','statusSessionSelect','statusFilter'].forEach(id=>$(id)?.addEventListener('change',()=>{ if(id==='statusEducationSelect') fillStatusSessionSelect(); renderStatus(); })); const modeWrap=$('exportMode')?.closest('div'); if(modeWrap) modeWrap.classList.add('hidden'); $('exportExcelBtn').addEventListener('click',()=>exportExcel().catch(e=>alertMsg(e.message))); $('exportPdfBtn').addEventListener('click',openPrintableSignatureSheet); $('exportPendingBtn').addEventListener('click',exportPendingCsv); }
function fillStatusSessionSelect(){ const eduId=$('statusEducationSelect')?.value; const sel=$('statusSessionSelect'); if(!sel) return; const prev=sel.value; sel.innerHTML='<option value="">전체</option>'; state.sessions.filter(s=>s.education_id===eduId).forEach(s=>{ const opt=document.createElement('option'); opt.value=s.id; opt.textContent=`${sessionLabel(s)} (${s.education_date||''})`; sel.appendChild(opt); }); if(prev && state.sessions.some(s=>s.id===prev)) sel.value=prev; }
function isSessionMode(){ return !!$('statusSessionSelect')?.value; }
function statusRows(){ const eduId=$('statusEducationSelect').value; const filter=$('statusFilter').value; const selectedSessionId=$('statusSessionSelect').value; if(!eduId) return []; const targetRecords=selectedSessionId ? targetsBySession(selectedSessionId) : targetsByEdu(eduId); return targetRecords.map(t=>{ const emp=getEmp(t.employee_id); if(!emp) return null; const sig=selectedSessionId ? signatureForSession(selectedSessionId,emp.id) : signatureFor(eduId,emp.id); const ses=sig ? getSession(sig.session_id) : null; return { employee:emp, signature:sig, session:ses }; }).filter(Boolean).filter(r=>filter==='completed'?!!r.signature:filter==='pending'?!r.signature:true); }
function renderStatus(){ fillStatusSessionSelect(); const eduId=$('statusEducationSelect').value; const selectedSessionId=$('statusSessionSelect').value; const targetRecords=eduId ? (selectedSessionId ? targetsBySession(selectedSessionId) : targetsByEdu(eduId)) : []; const total=targetRecords.length; const completed=eduId ? targetRecords.filter(t=>selectedSessionId ? signatureForSession(selectedSessionId,t.employee_id) : signatureFor(eduId,t.employee_id)).length : 0; const rows=statusRows(); const basis=selectedSessionId ? sessionLabel(getSession(selectedSessionId)) : '전체'; $('statusStats').innerHTML=`<div class="stat">출력 기준 ${escapeHtml(basis)}</div><div class="stat">대상 ${total}명</div><div class="stat">완료 ${completed}명</div><div class="stat">미완료 ${Math.max(total-completed,0)}명</div><div class="stat">현재표시 ${rows.length}명</div>`; const table=$('statusTable'); table.innerHTML=`<thead><tr><th>NO</th><th>부서</th><th>사번</th><th>이름</th><th>이수회차</th><th>서명</th><th>서명일시</th></tr></thead><tbody></tbody>`; const tb=table.querySelector('tbody'); rows.forEach((r,i)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${i+1}</td><td>${escapeHtml(r.employee.department)}</td><td>${escapeHtml(r.employee.employee_no)}</td><td>${escapeHtml(r.employee.name)}</td><td>${r.session?escapeHtml(sessionLabel(r.session)):'<span class="pill no">미완료</span>'}</td><td>${r.signature?`<img class="signature-img" src="${r.signature.signature_image_url}" />`:''}</td><td>${formatDateTime(r.signature?.signed_at)}</td>`; tb.appendChild(tr); }); }

function renderMyEducations(){ const list=$('myEducationList'); list.innerHTML=''; $('signaturePanel').classList.add('hidden'); const eduIds=[...new Set(state.targets.filter(t=>t.employee_id===currentEmployee.id).map(t=>t.education_id))]; const my=eduIds.map(id=>getEdu(id)).filter(Boolean).filter(e=>e.status!=='마감'); if(my.length===0){ list.innerHTML='<div class="panel">현재 서명 가능한 교육이 없습니다.</div>'; return; } my.forEach(edu=>{ const sig=signatureFor(edu.id,currentEmployee.id); const targetSessionIds=new Set(state.targets.filter(t=>t.education_id===edu.id&&t.employee_id===currentEmployee.id).map(t=>t.session_id)); const sessions=sessionsByEdu(edu.id).filter(s=>s.status==='서명가능'&&targetSessionIds.has(s.id)); const card=document.createElement('div'); card.className='card'; card.innerHTML=`<h3>${escapeHtml(edu.title)}</h3><p class="hint">${escapeHtml(edu.education_type||'')} · ${escapeHtml(edu.year||'')} · ${escapeHtml(edu.period||'')} ${escapeHtml(edu.period_detail||'')}</p><p>${sig?'<span class="pill ok">서명 완료</span>':'<span class="pill no">미서명</span>'} <span class="pill">서명 가능 회차 ${sig?0:sessions.length}개</span></p>`; const btn=document.createElement('button'); btn.className='primary'; btn.textContent=sig?'서명 내용 확인':'교육 확인 및 서명'; btn.onclick=()=>openSignaturePanel(edu.id); card.appendChild(btn); list.appendChild(card); }); }
function openSignaturePanel(educationId){ selectedSignEducationId=educationId; const edu=getEdu(educationId); const sig=signatureFor(educationId,currentEmployee.id); $('signaturePanel').classList.remove('hidden'); $('signEduTitle').textContent=edu.title; $('signEduMeta').textContent=`${edu.education_type||''} · ${edu.year||''} · ${edu.period||''} ${edu.period_detail||''}`; $('signEduSummary').textContent=edu.summary||'등록된 교육 요약내용이 없습니다.'; $('consentText').textContent=edu.consent_text||DEFAULT_CONSENT; $('consentCheck').checked=!!sig; const sel=$('signSessionSelect'); sel.innerHTML=''; const targetSessionIds=new Set(state.targets.filter(t=>t.education_id===educationId&&t.employee_id===currentEmployee.id).map(t=>t.session_id)); const available=sessionsByEdu(educationId).filter(s=>(s.status==='서명가능'&&targetSessionIds.has(s.id))||(sig&&sig.session_id===s.id)); available.forEach(s=>{ const opt=document.createElement('option'); opt.value=s.id; opt.textContent=`${sessionFullTitle(edu,s)} · ${s.education_date||''} ${s.start_time||''}~${s.end_time||''} · ${s.location||''}`; sel.appendChild(opt); }); if(sig) sel.value=sig.session_id; initSignatureCanvas(sig?.signature_image_url); $('submitSignatureBtn').disabled=!!sig; $('submitSignatureBtn').textContent=sig?'이미 제출 완료':'서명 제출'; $('clearSignatureBtn').disabled=!!sig; $('consentCheck').disabled=!!sig; $('signSessionSelect').disabled=!!sig; $('signaturePanel').scrollIntoView({behavior:'smooth',block:'start'}); }
function initSignatureCanvas(existingImage){ const canvas=$('signatureCanvas'); const ctx=canvas.getContext('2d'); ctx.clearRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.strokeStyle='#111827'; ctx.lineWidth=3; ctx.lineCap='round'; ctx.lineJoin='round'; let drawing=false, hasInk=false; function pos(evt){ const rect=canvas.getBoundingClientRect(); const e=evt.touches?evt.touches[0]:evt; return {x:(e.clientX-rect.left)*(canvas.width/rect.width),y:(e.clientY-rect.top)*(canvas.height/rect.height)}; } function start(evt){ if(existingImage) return; drawing=true; hasInk=true; const p=pos(evt); ctx.beginPath(); ctx.moveTo(p.x,p.y); evt.preventDefault(); } function move(evt){ if(!drawing||existingImage) return; const p=pos(evt); ctx.lineTo(p.x,p.y); ctx.stroke(); evt.preventDefault(); } function end(){ drawing=false; } canvas.onmousedown=start; canvas.onmousemove=move; window.onmouseup=end; canvas.ontouchstart=start; canvas.ontouchmove=move; canvas.ontouchend=end; signaturePad={canvas,ctx,hasInk:()=>hasInk||!!existingImage,clear:()=>{ if(existingImage) return; ctx.clearRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height); hasInk=false; },dataUrl:()=>canvas.toDataURL('image/png')}; if(existingImage){ const img=new Image(); img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height); img.src=existingImage; } }
function initSignatureActions(){ $('clearSignatureBtn').addEventListener('click',()=>signaturePad?.clear()); $('closeSignaturePanelBtn').addEventListener('click',()=>$('signaturePanel').classList.add('hidden')); $('submitSignatureBtn').addEventListener('click',async()=>{ try{ if(!selectedSignEducationId||!currentEmployee) return; if(signatureFor(selectedSignEducationId,currentEmployee.id)) return alertMsg('이미 제출된 서명은 수정할 수 없습니다.'); const sessionId=$('signSessionSelect').value; if(!sessionId) return alertMsg('서명 가능한 교육 회차가 없습니다.'); if(!targetsBySession(sessionId).some(t=>t.employee_id===currentEmployee.id)) return alertMsg('해당 회차의 교육 대상자가 아닙니다.'); if(!$('consentCheck').checked) return alertMsg('전자서명 동의 문구에 체크해 주세요.'); if(!signaturePad?.hasInk()) return alertMsg('서명을 입력해 주세요.'); const upload=await fetch('/api/upload-signature',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({educationId:selectedSignEducationId,sessionId,employeeId:currentEmployee.id,dataUrl:signaturePad.dataUrl()})}); const result=await upload.json(); if(!upload.ok) throw new Error(result.error||'서명 이미지 업로드 실패'); const sigPayload={ education_id:selectedSignEducationId, session_id:sessionId, employee_id:currentEmployee.id, consent_checked:true, signature_file_key:result.key, signature_image_url:result.url, ip_address:'vercel-api', device_info:navigator.userAgent }; const rows=await db('education_signatures',{method:'POST',body:sigPayload,prefer:'return=representation'}); state.signatures.push(rows[0]); alertMsg('서명이 제출되었습니다.'); await loadAllData(); renderMyEducations(); }catch(e){ alertMsg(e.message); } }); }

async function imageUrlToDataUrl(url){ if(!url) return ''; if(url.startsWith('data:')) return url; const res=await fetch(url); if(!res.ok) return ''; const blob=await res.blob(); return await new Promise(resolve=>{ const fr=new FileReader(); fr.onload=()=>resolve(fr.result); fr.readAsDataURL(blob); }); }
async function exportExcel(){ if(!window.ExcelJS) return alertMsg('ExcelJS 라이브러리를 불러오지 못했습니다.'); const eduId=$('statusEducationSelect').value; if(!eduId) return alertMsg('교육을 선택해 주세요.'); const edu=getEdu(eduId); const sessionId=$('statusSessionSelect').value; const rows=statusRows(); const selectedSession=sessionId?getSession(sessionId):null; const exportTitle=selectedSession?sessionFullTitle(edu,selectedSession):edu.title; const wb=new ExcelJS.Workbook(); wb.creator='Education Signature Manager'; const ws=wb.addWorksheet('Signature Sheet',{pageSetup:{paperSize:9,orientation:'portrait',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:0.3,right:0.3,top:0.5,bottom:0.5,header:0.2,footer:0.2}}}); ws.columns=[{key:'no',width:6},{key:'dept',width:20},{key:'empno',width:14},{key:'name',width:14},{key:'session',width:22},{key:'signature',width:24},{key:'signedAt',width:22}]; ws.mergeCells('A1:G1'); ws.getCell('A1').value='서명부'; ws.getCell('A1').font={bold:true,size:18}; ws.getCell('A1').alignment={horizontal:'center'}; ws.mergeCells('A2:G2'); ws.getCell('A2').value=`교육명: ${exportTitle}`; ws.mergeCells('A3:G3'); ws.getCell('A3').value=`교육구분: ${edu.education_type||''} / 연도: ${edu.year||''} / 주기: ${edu.period||''}`; ws.mergeCells('A4:G4'); ws.getCell('A4').value=selectedSession?`출력기준: ${sessionLabel(selectedSession)} / ${selectedSession.education_date||''} ${selectedSession.start_time||''}~${selectedSession.end_time||''} / ${selectedSession.location||''}`:'출력기준: 전체'; ws.addRow([]); const header=ws.addRow(['NO','부서','사번','이름','이수회차','서명','서명일시']); header.font={bold:true}; header.height=22; header.eachCell(cell=>{ cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFEFF3F8'}}; cell.border=thinBorder(); cell.alignment={horizontal:'center',vertical:'middle'}; }); const startRow=ws.lastRow.number+1; for(const [idx,r] of rows.entries()){ const row=ws.addRow([idx+1,r.employee.department,r.employee.employee_no,r.employee.name,r.session?sessionLabel(r.session):'미완료','',formatDateTime(r.signature?.signed_at)]); row.height=48; row.eachCell(cell=>{ cell.border=thinBorder(); cell.alignment={horizontal:'center',vertical:'middle'}; }); if(r.signature?.signature_image_url){ const dataUrl=await imageUrlToDataUrl(r.signature.signature_image_url); if(dataUrl){ const imageId=wb.addImage({base64:dataUrl,extension:'png'}); ws.addImage(imageId,{tl:{col:5.15,row:startRow+idx-0.85},ext:{width:145,height:42},editAs:'oneCell'}); } } } ws.eachRow(row=>row.eachCell(cell=>{ cell.font={...(cell.font||{}),name:'Malgun Gothic'}; })); const buf=await wb.xlsx.writeBuffer(); saveAs(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),safeFileName(`signature_sheet_${exportTitle}.xlsx`)); }
function openPrintableSignatureSheet(){ const eduId=$('statusEducationSelect').value; if(!eduId) return alertMsg('교육을 선택해 주세요.'); const edu=getEdu(eduId); const rows=statusRows(); const sessionId=$('statusSessionSelect').value; const selectedSession=sessionId?getSession(sessionId):null; const exportTitle=selectedSession?sessionFullTitle(edu,selectedSession):edu.title; const info=selectedSession?`회차별 서명부 · ${sessionLabel(selectedSession)} · ${selectedSession.education_date||''} ${selectedSession.start_time||''}~${selectedSession.end_time||''} · ${selectedSession.location||''}`:'전체 통합 서명부'; const perPage=18; const pages=[]; for(let i=0;i<rows.length;i+=perPage) pages.push(rows.slice(i,i+perPage)); const html=(pages.length?pages:[[]]).map((page,pi)=>`<section class="print-page"><h1>서명부</h1><div class="meta"><p><b>교육명:</b> ${escapeHtml(exportTitle)}</p><p><b>교육구분:</b> ${escapeHtml(edu.education_type||'')} / <b>연도:</b> ${escapeHtml(edu.year||'')} / <b>주기:</b> ${escapeHtml(edu.period||'')}</p><p><b>출력기준:</b> ${escapeHtml(info)}</p></div><table><thead><tr><th>NO</th><th>부서</th><th>사번</th><th>이름</th><th>이수회차</th><th>서명</th><th>서명일시</th></tr></thead><tbody>${page.map((r,idx)=>`<tr><td>${pi*perPage+idx+1}</td><td>${escapeHtml(r.employee.department)}</td><td>${escapeHtml(r.employee.employee_no)}</td><td>${escapeHtml(r.employee.name)}</td><td>${r.session?escapeHtml(sessionLabel(r.session)):'미완료'}</td><td>${r.signature?`<img src="${r.signature.signature_image_url}" />`:''}</td><td>${formatDateTime(r.signature?.signed_at)}</td></tr>`).join('')}</tbody></table><div class="page-no">${pi+1} / ${pages.length||1}</div></section>`).join(''); const win=window.open('','_blank'); win.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>Signature Sheet</title><style>@page{size:A4;margin:12mm} body{font-family:Arial,'Malgun Gothic',sans-serif;color:#111}.print-page{page-break-after:always}h1{text-align:center;margin:0 0 12px;font-size:22px}.meta{font-size:12px;margin-bottom:10px}.meta p{margin:3px 0}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #222;padding:6px;text-align:center;vertical-align:middle;font-size:11px;height:38px}th{background:#eee}td:nth-child(2){text-align:left}img{max-width:120px;max-height:34px}.page-no{text-align:right;margin-top:8px;font-size:11px;color:#555}@media print{.print-page:last-child{page-break-after:auto}}</style></head><body>${html}<script>setTimeout(()=>window.print(),300)<\/script></body></html>`); win.document.close(); }
function exportPendingCsv(){ const eduId=$('statusEducationSelect').value; if(!eduId) return alertMsg('교육을 선택해 주세요.'); const edu=getEdu(eduId); const sessionId=$('statusSessionSelect').value; const records=sessionId?targetsBySession(sessionId):targetsByEdu(eduId); const rows=records.map(t=>getEmp(t.employee_id)).filter(Boolean).filter(e=>sessionId?!signatureForSession(sessionId,e.id):!signatureFor(eduId,e.id)); const basis=sessionId?sessionFullTitle(edu,getSession(sessionId)):'전체'; const csvRows=[['교육명','출력기준','부서','사번','이름','휴대폰번호','근무형태'],...rows.map(e=>[edu.title,basis,e.department,e.employee_no,e.name,e.phone_number,e.shift_type])]; const csv='\ufeff'+csvRows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); saveAs(blob,safeFileName(`pending_${edu.title}_${basis}.csv`)); }

function initReset(){ $('resetAllBtn')?.addEventListener('click',()=>alertMsg('Supabase 연결 버전에서는 전체 초기화를 비활성화했습니다. 필요한 경우 Supabase에서 직접 백업 후 삭제해 주세요.')); }
async function boot(){ try{ await initConfig(); initTabs(); initNav(); initLogins(); initEmployeeActions(); initEducationActions(); initSessionActions(); initTargetActions(); initStatusActions(); initSignatureActions(); initReset(); clearEducationForm(true); showLogin(); }catch(e){ document.body.innerHTML=`<main class="app"><div class="panel"><h2>초기화 오류</h2><p>${escapeHtml(e.message)}</p></div></main>`; } }
boot();
