(function(){
  function isMobile(){return /Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'') || (window.matchMedia&&window.matchMedia('(pointer: coarse)').matches&&window.innerWidth<=900)}
  function g(id){return document.getElementById(id)}
  function clean(v){return String(v||'').replace(/[^0-9]/g,'')}
  function styleLink(){var a=g('octomoSmsLink');if(!a)return;a.textContent='(모바일) 문자 앱 열기';a.style.display='flex';a.style.alignItems='center';a.style.justifyContent='center';a.style.minHeight='50px';a.style.marginTop='14px';a.style.borderRadius='12px';a.style.background='#43cb3b';a.style.border='1px solid #43cb3b';a.style.color='#fff';a.style.textDecoration='none';a.style.fontWeight='900';a.style.boxShadow='0 8px 18px rgba(67,203,59,.22)';a.style.fontSize='15px'}
  function findCode(box){var nodes=box.querySelectorAll('div');for(var i=0;i<nodes.length;i++){if((nodes[i].textContent||'').trim()==='인증코드'&&nodes[i+1])return (nodes[i+1].textContent||'').trim()}return ''}
  async function apply(){var box=g('octomoVerifyBox');if(!box)return;styleLink();if(isMobile())return;if(box.dataset.pcqr==='1')return;box.dataset.pcqr='1';var link=g('octomoSmsLink');if(link)link.style.display='none';var code=findCode(box);var holder=document.createElement('div');holder.className='octomo-qr-card';holder.innerHTML='<div class="octomo-qr-title">휴대폰 카메라로 스캔</div><div class="octomo-qr-status">QR 코드 생성 중...</div>';var check=g('octomoCheckBtn');box.insertBefore(holder,check||null);try{var res=await fetch('/api/octomo-qr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:code})});var data=await res.json().catch(function(){return{}});if(!res.ok||!data.qrCode)throw new Error(data.error||'QR 생성 실패');holder.innerHTML='<div class="octomo-qr-title">휴대폰 카메라로 스캔</div><img src="'+data.qrCode+'" alt="SMS QR"><div class="octomo-qr-status">문자 앱에 수신번호와 인증코드가 자동 입력됩니다.</div>'}catch(e){holder.innerHTML='<div class="octomo-qr-status">QR 생성에 실패했습니다. 수신번호와 인증코드를 직접 문자로 보내 주세요.</div>'}}
  async function safeStart(ev){var b=g('employeeLoginBtn');if(!b)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();var old=b.textContent;b.disabled=true;b.textContent='인증코드 발급 중...';var c=new AbortController(), t=setTimeout(function(){c.abort()},8000);try{var name=(g('empLoginName').value||'').trim(), no=(g('empLoginNo').value||'').trim(), ph=clean(g('empLoginPhone').value);if(!name||!no||!ph)throw Error('이름, 사번, 휴대폰 번호를 모두 입력해 주세요.');var r=await fetch('/api/octomo-start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name,employeeNo:no,phone:ph}),signal:c.signal});var d=await r.json().catch(function(){return{}});if(!r.ok)throw Error(d.error||'본인인증 시작 실패');window.__octomoLast=d;if(typeof showOctomoBox==='function')showOctomoBox(d);else alert('인증코드: '+d.code+' / 수신번호: '+d.receiverNumber)}catch(e){alert(e.name==='AbortError'?'인증 요청 시간이 초과되었습니다. 잠시 후 다시 시도해 주세요.':(e.message||e))}finally{clearTimeout(t);b.disabled=false;b.textContent=old}}
  window.addEventListener('click',function(ev){var t=ev.target;if(t&&t.closest&&t.closest('#employeeLoginBtn'))safeStart(ev)},true);
  new MutationObserver(apply).observe(document.documentElement,{childList:true,subtree:true});
  document.addEventListener('DOMContentLoaded',apply);
  setInterval(apply,1000);
})();
