(function(){
  var last=null;
  function el(id){return document.getElementById(id)}
  function v(id){var x=el(id);return x?String(x.value||'').trim():''}
  function digits(s){return String(s||'').replace(/[^0-9]/g,'')}
  function mobile(){return /Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'') || (matchMedia&&matchMedia('(pointer: coarse)').matches&&innerWidth<=900)}
  function box(){var b=el('octomoVerifyBox');if(!b){b=document.createElement('div');b.id='octomoVerifyBox';var btn=el('employeeLoginBtn');if(btn&&btn.parentNode)btn.parentNode.insertBefore(b,btn.nextSibling)}b.style.cssText='display:block;margin-top:16px;padding:16px;border:1px solid #d9dee8;border-radius:16px;background:#fff;box-shadow:0 6px 18px rgba(30,41,59,.06);line-height:1.5';return b}
  function post(url,body,ms){var c=new AbortController();var t=setTimeout(function(){c.abort()},ms||8000);return fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal}).finally(function(){clearTimeout(t)})}
  function sms(to,code){return ('s'+'m'+'s:')+digits(to)+'?&body='+encodeURIComponent(code)}
  function draw(d){last=d;var b=box();var base='<b>휴대폰 본인인증</b><p style="margin:8px 0 10px;color:#334155">'+(mobile()?'아래 버튼을 누르면 문자 앱이 열립니다. 문자 앱에서 전송만 눌러주세요.':'PC에서는 아래 QR 코드를 휴대폰 카메라로 스캔해 주세요.')+'</p><div style="display:grid;grid-template-columns:90px 1fr;gap:6px;margin:8px 0"><div>수신번호</div><div><b>'+d.receiverNumber+'</b></div><div>인증코드</div><div style="font-size:24px;font-weight:800;letter-spacing:2px">'+d.code+'</div></div>';
    if(mobile()){b.innerHTML=base+'<a href="'+sms(d.receiverNumber,d.code)+'" style="display:flex;align-items:center;justify-content:center;width:100%;min-height:50px;margin-top:14px;border-radius:12px;background:#43cb3b;border:1px solid #43cb3b;color:#fff;text-decoration:none;font-weight:900;box-shadow:0 8px 18px rgba(67,203,59,.22)">(모바일) 문자 앱 열기</a><button class="primary full" id="octomoCheckBtn" type="button">전송 후 인증 확인</button><button class="full" id="octomoRestartBtn" type="button">인증코드 다시 받기</button>'}
    else{b.innerHTML=base+'<div id="octomoQr" style="display:flex;flex-direction:column;align-items:center;gap:10px;margin-top:12px;padding:14px;border:1px solid #dbe3ef;border-radius:14px;background:#f8fafc"><b>QR 코드 생성 중...</b></div><button class="primary full" id="octomoCheckBtn" type="button">전송 후 인증 확인</button><button class="full" id="octomoRestartBtn" type="button">인증코드 다시 받기</button>';loadQr(d)}
    el('octomoCheckBtn').onclick=check;el('octomoRestartBtn').onclick=start;
  }
  async function loadQr(d){try{var r=await post('/api/octomo-qr',{text:d.code},8000);var j=await r.json();if(!r.ok||!j.qrCode)throw Error(j.error||'QR 생성 실패');el('octomoQr').innerHTML='<b>휴대폰 카메라로 스캔</b><img src="'+j.qrCode+'" style="width:180px;height:180px;object-fit:contain;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:8px"><div style="color:#64748b;font-size:13px">문자 앱에 자동 입력됩니다.</div>'}catch(e){el('octomoQr').innerHTML='<div style="color:#64748b;font-size:13px">QR 생성 실패. 직접 문자로 보내 주세요.</div>'}}
  async function start(){var btn=el('employeeLoginBtn'), old=btn?btn.textContent:'';try{if(btn){btn.disabled=true;btn.textContent='인증코드 발급 중...'}var name=v('empLoginName'), no=v('empLoginNo'), ph=digits(v('empLoginPhone'));if(!name||!no||!ph)throw Error('이름, 사번, 휴대폰 번호를 모두 입력해 주세요.');var r=await post('/api/octomo-start',{name:name,employeeNo:no,phone:ph},8000);var d=await r.json().catch(function(){return{}});if(!r.ok)throw Error(d.error||'본인인증 시작 실패');draw(d)}catch(e){alert(e.name==='AbortError'?'인증 요청 시간이 초과되었습니다. 잠시 후 다시 시도해 주세요.':(e.message||e))}finally{if(btn){btn.disabled=false;btn.textContent=old}}}
  async function check(){try{if(!last||!last.verificationId)throw Error('먼저 인증코드를 발급해 주세요.');var r=await post('/api/octomo-check',{verificationId:last.verificationId},10000);var d=await r.json().catch(function(){return{}});if(!r.ok)throw Error(d.error||'본인인증 확인 실패');if(!d.verified){alert(d.error||'아직 인증 문자가 확인되지 않았습니다.');return}state=d.state;currentEmployee=d.employee;await showEmployee(d.employee)}catch(e){alert(e.name==='AbortError'?'인증 확인 시간이 초과되었습니다.':(e.message||e))}}
  document.addEventListener('click',function(ev){var t=ev.target;if(t&&t.closest&&t.closest('#employeeLoginBtn')){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();start()}},true);
})();
